### ISSUE TITLE
Add environment variables using action inputs

### ISSUE THREAD

**Issue by amira-d** [plotly/de-deploy#20]
In some cases, an environment variable is necessary for the app to deploy/run correctly (e.g DB credentials). 
I suggest adding a separate step right after creating the app that might look like this. 
The condition for when to run this step can also depend on whether any ENV_VARIABLEs have been configured 

```
- name: Set up DE application environment
        shell: bash
        if: github.event.action != 'closed'
        run: |
          IFS = $VAR_SEPERATOR
          for env in $(read -ra env <<< $ENV_VARIABLES) ; do
          de --no-keyfile apps update --name  ${{ env.APP_NAME }} --add-environment-variable $env
          done
        env:
          DASH_ENTERPRISE_HOST: ${{ vars.DASH_ENTERPRISE_URL }}
          DASH_ENTERPRISE_USERNAME: ${{ vars.DASH_ENTERPRISE_USERNAME }}
          DASH_ENTERPRISE_PASSWORD: ${{ secrets.DASH_ENTERPRISE_PASSWORD }}
          APP_NAME: ${{ vars.APP_NAME }}
          ENV_VARIABLES: ${{ secrets.ENV_VARIABLES }}
          VAR_SEPERATOR: ${{ vars.VAR_SEPERATOR }}
```
